name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Build
      run: dotnet build src/GrpcProxy/GrpcProxy.csproj --configuration ${{ env.CONFIGURATION }} --no-self-contained
    - name: Test
      run: dotnet test src/tests/GrpcProxy.Tests/GrpcProxy.Tests.csproj --configuration ${{ env.CONFIGURATION }}